[package]
name = "mcio"
version = "0.1.1"
authors = ["Alex A. <alex@tsanga.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
